apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testnet-manager.fullname" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}