{{- $fullName := include "testnet-manager.fullname" . -}}
{{- $serviceAccountName := include "testnet-manager.fullname" . -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName | default $fullName }}
  labels:
    {{- include "testnet-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
