{{- if .Values.ingress.core.enabled -}}
{{- $fullName := include "substrate-telemetry.fullname" . -}}
{{- $svcPort := .Values.service.core.port -}}
{{- if and .Values.ingress.core.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.core.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.core.annotations "kubernetes.io/ingress.class" .Values.ingress.core.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: telemetry-core
  labels:
    {{- include "substrate-telemetry.labels" . | nindent 4 }}
    telemetry-component: core
  {{- with .Values.ingress.core.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.core.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.core.className }}
  {{- end }}
  rules:
  {{- with .Values.ingress.core.rules }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- if .Values.ingress.core.tls }}
  tls:
  {{- with .Values.ingress.core.tls }}
  {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- end }}
{{- end }}
