apiVersion: v1
kind: Service
metadata:
  name: telemetry-core
  labels:
    {{- include "substrate-telemetry.labels" . | nindent 4 }}
    telemetry-component: core
  annotations:
    {{- toYaml .Values.service.core.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.core.type }}
  ports:
    - port: {{ .Values.service.core.port }}
      targetPort: {{ .Values.service.core.targetPort }}
      protocol: TCP
      name: http
{{- if (and (eq .Values.service.core.type "NodePort") (not (empty .Values.service.core.nodePort))) }}
      nodePort: {{ .Values.service.core.nodePort }}
{{- end }}
  selector:
    {{- include "substrate-telemetry.selectorLabels" . | nindent 4 }}
    telemetry-component: core
