apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-shard
  labels:
    {{- include "substrate-telemetry.labels" . | nindent 4 }}
    telemetry-component: shard
spec:
  {{- if not .Values.autoscaling.shard.enabled }}
  replicas: {{ .Values.replicaCount.shard }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "substrate-telemetry.selectorLabels" . | nindent 6 }}
      telemetry-component: shard
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "substrate-telemetry.selectorLabels" . | nindent 8 }}
        telemetry-component: shard
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "substrate-telemetry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          {{- if .Values.envVars.shard }}
          env:
          {{- range $key, $val := .Values.envVars.shard }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          command:
            - "telemetry_shard"
          args:
            - "--listen"
            - "0.0.0.0:{{ .Values.service.shard.targetPort }}"
            - "--core"
            - "http://telemetry-core:{{ .Values.service.core.port }}/shard_submit"
            {{-  range .Values.extraArgs.shard }}
            - {{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.shard.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources.shard | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
