{{ $fullname :=  include "node.fullname" . }}
{{ $selectorLabels :=  include "node.selectorLabels" .  }}
{{ $serviceLabels :=  include "node.serviceLabels" .  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- $selectorLabels | nindent 4 }}
  ports:
    {{- if $.Values.node.substrateApiSidecar.enabled }}
    - port: 8080
      name: api-sidecar
    {{- end }}
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
---
{{range $i := until (.Values.node.replicas | int) }}
{{- if or $.Values.node.perNodeServices.createApiService $.Values.node.perNodeServices.createClusterIPService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}
  labels:
    {{- $serviceLabels | nindent 4 }}
    node: {{ $fullname }}-{{ $i }}
    instance: {{ $fullname }}-{{ $i }}
{{- with $.Values.node.perNodeServices.apiServiceAnnotations }}
  annotations:
{{ toYaml . | indent 4}}
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
    - port: 9615
      name: prometheus
{{- end }}
---
{{- if or $.Values.node.perNodeServices.createP2pService $.Values.node.perNodeServices.createP2pNodePortService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}-relay-chain-p2p
{{- with $.Values.node.perNodeServices.relayServiceAnnotations }}
  annotations:
{{ toYaml . | indent 4}}
{{- end }}
spec:
  {{- if eq $.Values.node.perNodeServices.p2pServiceType "NodePort" }}
  type: NodePort
  externalTrafficPolicy: Local
  {{- else if eq $.Values.node.perNodeServices.p2pServiceType "ClusterIP" }}
  type: ClusterIP
  {{- else if eq $.Values.node.perNodeServices.p2pServiceType "LoadBalancer" }}
  type: LoadBalancer
  {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - name: p2p
      port: 30333
      targetPort: 30333
{{- end }}
---
{{- if and $.Values.node.collator.isParachain (or $.Values.node.perNodeServices.createP2pService $.Values.node.perNodeServices.createP2pNodePortService) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}-para-chain-p2p
{{- with $.Values.node.perNodeServices.paraServiceAnnotations }}
  annotations:
{{ toYaml . | indent 4}}
{{- end }}
spec:
  {{- if eq $.Values.node.perNodeServices.p2pServiceType "NodePort" }}
  type: NodePort
  externalTrafficPolicy: Local
  {{- else if eq $.Values.node.perNodeServices.p2pServiceType "ClusterIP" }}
  type: ClusterIP
  {{- else if eq $.Values.node.perNodeServices.p2pServiceType "LoadBalancer" }}
  type: LoadBalancer
  {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - name: p2p
      port: 30334
      targetPort: 30334
{{- end }}
---
{{ end }}
