{{ $fullname :=  include "chart.fullname" . }}
{{ $selectorLabels :=  include "chart.selectorLabels" .  }}
{{ $serviceLabels :=  include "chart.serviceLabels" .  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- $selectorLabels | nindent 4 }}
  ports:
    - port: 8080
      name: api-sidecar
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
    - port: 9615
      name: prometheus
    - port: 30333
      name: p2p
---
{{range $i := until (.Values.node.replicas | int) }}
{{- if $.Values.node.perNodeServices.createClusterIPService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}
  labels: 
    {{- $serviceLabels | nindent 4 }}
    instance: {{ $fullname }}-{{ $i }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
    - port: 9615
      name: prometheus
{{- end }}
---
{{- if $.Values.node.perNodeServices.createP2pNodePortService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}-p2p
spec:
  type: NodePort
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - name: p2p
      port: {{ add $.Values.node.perNodeServices.p2pNodePortStartRange $i }}
      nodePort: {{ add $.Values.node.perNodeServices.p2pNodePortStartRange $i }}
      targetPort: 30333
{{- end }}
---
{{ end }}
