{{- if not .Values.runtimeExporter.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
type: Opaque
data:
  TSDB_CONN: {{ .Values.runtimeExporter.secret.tsdbConnectionUrl | b64enc | quote }}
{{- end }}