apiVersion: v2
name: polkadot-runtime-exporter
description: A Helm chart to deploy runtime exporter (https://github.com/paritytech/polkadot-runtime-prom-exporter)
type: application
version: 1.0.2
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
dependencies:
- name: common
  version: 1.14.1
  repository: https://charts.bitnami.com/bitnami
