apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: polkadot-archive
  ports:
    - port: 8080
      name: api-sidecar
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
    - port: 9615
      name: prometheus
    - port: 30333
      name: p2p
