apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot-introspector.fullname" . }}
  labels:
    {{- include "polkadot-introspector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: prometheus
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.introspector.prometheusPort }}
      protocol: TCP
  selector:
    {{- include "polkadot-introspector.selectorLabels" . | nindent 4 }}