apiVersion: v2
name: testnet-manager
description: A Helm chart to deploy testnet-manager
type: application
version: 1.1.2
appVersion: "1.2.1"
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
